AppBundle\Entity\Blog:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\BlogRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text

    manyToOne:
        user:
            targetEntity: User
            inversedBy: blogs
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
