AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true

        password:
            type: string
            length: 255

    oneToOne:
        token:
          targetEntity: Token
          mappedBy: user

    oneToMany:
        blogs:
          targetEntity: Blog
          mappedBy: user

    lifecycleCallbacks: {  }
