app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:homepage

users:
    type:     rest
    resource: AppBundle\Controller\UserController

blog:
    type:     rest
    resource: AppBundle\Controller\BlogController
